### ISSUE TITLE
Redirection and piping doesn't work

### ISSUE THREAD

**Issue by jarun** [jarun/google-cli#13]
Currently redirection and piping doesn't work.

Issues:

<pre>$ googler hello > out.txt
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 309, in <module>
    winsz = fcntl.ioctl(sys.stdout, termios.TIOCGWINSZ, "1234")
IOError: [Errno 25] Inappropriate ioctl for device

$ googler hello | tee out.txt
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 309, in <module>
    winsz = fcntl.ioctl(sys.stdout, termios.TIOCGWINSZ, "1234")
IOError: [Errno 25] Inappropriate ioctl for device

$ googler hello | tail
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 309, in <module>
    winsz = fcntl.ioctl(sys.stdout, termios.TIOCGWINSZ, "1234")
IOError: [Errno 25] Inappropriate ioctl for device<pre>

**Comment by jarun** [comment]
Fixed at https://github.com/jarun/google-cli/commit/08d788a1baa10e4acd0bdcd99f33d95cd11ad39f.
